### ISSUE TITLE
NPE in ApplyMisfire

### ISSUE THREAD

**Issue by AgnibhaBose** [jlinn/quartz-redis-jobstore#35]
Hi I am Getting This issue.

```
Caused by: java.lang.NullPointerException
	at net.joelinn.quartz.jobstore.AbstractRedisStorage.applyMisfire(AbstractRedisStorage.java:565)
	at net.joelinn.quartz.jobstore.AbstractRedisStorage.acquireNextTriggers(AbstractRedisStorage.java:819)
	at net.joelinn.quartz.jobstore.RedisJobStore$39.doWithLock(RedisJobStore.java:1041)
	at net.joelinn.quartz.jobstore.RedisJobStore$39.doWithLock(RedisJobStore.java:1037)
	at net.joelinn.quartz.jobstore.RedisJobStore.doWithLock(RedisJobStore.java:1154)
	... 2 more
```

Code that I am Executing

```
public class TestQuartzWithRedis {
    public static void main (String[] args) throws SchedulerException, InterruptedException {
        Scheduler scheduler = StdSchedulerFactory.getDefaultScheduler();
        scheduler.start();

        Date startTime = DateBuilder.futureDate(5000, DateBuilder.IntervalUnit.MILLISECOND);

        JobDetail job = JobBuilder
                .newJob(SampleJob.class)
                .withIdentity(UUID.randomUUID().toString(), "messageGroup")
                .requestRecovery()
                .build();

        SimpleTrigger trigger = (SimpleTrigger) newTrigger()
                .forJob(job)
                .withIdentity("trigger:" + UUID.randomUUID().toString(), "messageGroup")
                .startAt(startTime)
                .build();
        scheduler.scheduleJob(job, trigger);

    }
}
```

**Comment by jlinn** [comment]
Ah, I see.  You've got a `:` in your trigger name.  `:` is the default delimiter for the Redis keys used by the jobstore.  If you intend to use those in your trigger names, you should configure a different delimiter (`$$`, for example):
```
org.quartz.jobStore.keyDelimeter = $$
```

**Comment by AgnibhaBose** [comment]
Yes but it fails for other special characters too... Like +

**Comment by AgnibhaBose** [comment]
@jlinn I am Getting this issue again if I set org.quartz.scheduler.instanceId to AUTO and My InetAddress.getLocalHost().getHostName() contains special characters.

**Comment by AgnibhaBose** [comment]
```
 public static String getUniqueIdentifier(String schedName,
            String schedInstId) {
        return schedName + "_$_" + schedInstId;
}
```

This is the method in quartz that generates unique identifier
